dist: ubuntu trusty
git:
  depth: 3
language: php
php:
- '7.1'
cache:
  yarn: true
  directories:
  - "$HOME/.composer/cache"
  - "$HOME/node_modules"
services:
  - redis-server
before_install:
- nvm install 7
- nvm use 7
- npm cache clean
- npm install
before_script:
- touch /home/travis/build/HomeHero/harvey/harvey.sqlite
- phpenv config-rm xdebug.ini
- composer self-update
- composer install --no-interaction
script:
- vendor/bin/phpunit
branches:
  only:
  - master
  - develop
  - /-release$/
notifications:
  email: false
  slack:
    rooms:
      secure: IPwRGtt3SVK8MvcVLulMdVOmrCfMly5GZt0YU5L6fmX8AXKRHLj99RwDwJ+pHuFPmrDrxphxaxeBhhf6kzYI4em0MYBaqfsAk0XsdOLY+7WoF/Bu5T1xGKsjgmHQpEzHhwTrghboGoSw3Op2o2x5FgvhMi6Bg03Lmp73As1yB4mIPb6z9x9PxYeS9UNsTBiyyFpV9r7pVLzSMrwKZXfaaaHkKScto0RKcg7aovtKphWlsuxGLOXejcZU9DFV7QBX8oFZmsTc1Qlga/3SD0VjlNU7wlHLTxZR9qWj7pOyssU2XEjCCET77MypifMA/vNysdG/VWturDSSJZ3yeeFpJTbgMwpXK+SYj+2yHc59z9RZFLoQ3nDmopFjsnz04ypcuDWLt6L0pQcOtiVbqcTLJpCTAAvoClMIVIVy9O1xSqj8S3ZIj6rXxVsGxVnlbhNJXKv+aQUrglbSmdlsQmtEz6W1e8x+sqj8WLXUN6WWuxqgOhEDXKvJ6VjWblo2YjKGJMcmSbadsdRO6Px8yMgSUj9d/jz8QcGjo+yb05Omz2YRBpUWnBTCn+p3E7wJFAAi0qtdhdHHqmiBs1+rWRMFrY/r7GTps3bLuI5p5QXOyqdvuTiZtparlGgdWjo8sZRJeJaBVg8rhAxqM9bpuR+NiR+SzqC8RMg8i8n56pVO1dI=
    template:
      - "%{commit_message} on `%{branch}` by %{author}: %{message}"
      - "Elapsed Time: %{elapsed_time}"
      - "Build details: %{build_url}"
