dist: trusty
sudo: required
git:
  depth: 3
language: php
php:
- '7.1'
cache:
  yarn: true
  directories:
  - "$HOME/.composer/cache"
before_install:
- bash .travis.install-mysql-5.7.sh
- cp .env.dusk.local .env
- nvm install 7.4.0
- nvm use 7.4.0
- npm cache clean
- npm install
- mysql -e 'CREATE DATABASE harvey_dusk;'
before_script:
- export DB_CONNECTION=mysql
- export DB_USERNAME=root
- export DB_DATABASE=harvey_dusk
- export DB_SOCKET=/var/run/mysqld/mysqld.sock
- phpenv config-rm xdebug.ini
- composer self-update
- composer install --no-interaction
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- ./vendor/laravel/dusk/bin/chromedriver-linux --silent &
script:
- php artisan migrate --seed
- php artisan serve --host=localhost --quiet > /dev/null 2>&1 &
- php artisan dusk
branches:
  only:
  - master
  - develop
  - dusk
  - /^release\//
notifications:
  email: false
