dist: trusty
sudo: required
git:
  depth: 3
language: php
php:
- '7.1'
cache:
  yarn: true
  directories:
  - "$HOME/.composer/cache"
before_install:
- nvm install 7.4.0
- nvm use 7.4.0
- npm cache clean
- npm install
- mysql -e 'CREATE DATABASE harvey;'
before_script:
- phpenv config-rm xdebug.ini
- composer self-update
- composer install --no-interaction
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- ./vendor/laravel/dusk/bin/chromedriver-linux --silent &
services:
  - mysql
script:
- php artisan migrate --seed
- php artisan serve --host=localhost &
- vendor/bin/phpunit
- touch .env
- php artisan dusk
branches:
  only:
  - master
  - develop
  - dusk
  - /^release\//
