dist: ubuntu trusty
sudo: required
git:
  depth: 3
language: php
php:
- '7.1'
cache:
  yarn: true
  directories:
  - "$HOME/.composer/cache"
  - "$HOME/node_modules"
services:
- redis-server
- mysql:
  environment:
    MYSQL_ROOT_PASSWORD: secret
    MYSQL_DATABASE: harvey
    MYSQL_USER: homestead
    MYSQL_PASSWORD: secret


before_install:
- nvm install 7
- nvm use 7
- npm cache clean
- npm install npm@latest -g
- npm install
- touch /home/travis/build/HomeHero/harvey/harvey_dusk.sqlite
- cp .env.dusk.travis .env
before_script:
- touch /home/travis/build/HomeHero/harvey/harvey.sqlite
- export DB_CONNECTION=sqlite
- export DB_DATABASE=/home/travis/build/HomeHero/harvey/harvey_dusk.sqlite
- phpenv config-rm xdebug.ini
- composer install --no-interaction
- export DISPLAY=:99.0
- /usr/bin/Xvfb :99 -ac -screen 0 2560x1440x24 &
- ./vendor/laravel/dusk/bin/chromedriver-linux --silent &
script:
- php artisan migrate --seed
- php artisan passport:install --force
- php artisan serve --host=localhost --quiet > /dev/null 2>&1 &
- php artisan dusk
- sudo killall -s SIGKILL Xvfb chromedriver-linux php
- php artisan passport:getkeys
- vendor/bin/phpunit
- rm .env

branches:
  only:
  - master
  - develop
  - dusk-tests
  - staging
  - /^release\//
notifications:
  email: false
  slack:
    rooms:
      secure: IPwRGtt3SVK8MvcVLulMdVOmrCfMly5GZt0YU5L6fmX8AXKRHLj99RwDwJ+pHuFPmrDrxphxaxeBhhf6kzYI4em0MYBaqfsAk0XsdOLY+7WoF/Bu5T1xGKsjgmHQpEzHhwTrghboGoSw3Op2o2x5FgvhMi6Bg03Lmp73As1yB4mIPb6z9x9PxYeS9UNsTBiyyFpV9r7pVLzSMrwKZXfaaaHkKScto0RKcg7aovtKphWlsuxGLOXejcZU9DFV7QBX8oFZmsTc1Qlga/3SD0VjlNU7wlHLTxZR9qWj7pOyssU2XEjCCET77MypifMA/vNysdG/VWturDSSJZ3yeeFpJTbgMwpXK+SYj+2yHc59z9RZFLoQ3nDmopFjsnz04ypcuDWLt6L0pQcOtiVbqcTLJpCTAAvoClMIVIVy9O1xSqj8S3ZIj6rXxVsGxVnlbhNJXKv+aQUrglbSmdlsQmtEz6W1e8x+sqj8WLXUN6WWuxqgOhEDXKvJ6VjWblo2YjKGJMcmSbadsdRO6Px8yMgSUj9d/jz8QcGjo+yb05Omz2YRBpUWnBTCn+p3E7wJFAAi0qtdhdHHqmiBs1+rWRMFrY/r7GTps3bLuI5p5QXOyqdvuTiZtparlGgdWjo8sZRJeJaBVg8rhAxqM9bpuR+NiR+SzqC8RMg8i8n56pVO1dI=
    template:
      - "%{commit_message} on `%{branch}` by %{author}: %{message}"
      - "Elapsed Time: %{elapsed_time}"
      - "Build details: %{build_url}"
