export default {
  "id": "card_1BK8dIBsfa0DD4bHn8fqEEF3",
  "object": "card",
  "address_city": null,
  "address_country": null,
  "address_line1": null,
  "address_line1_check": null,
  "address_line2": null,
  "address_state": null,
  "address_zip": "45420",
  "address_zip_check": "pass",
  "brand": "Visa",
  "country": "US",
  "customer": "cus_BhXibMAn3zCxEU",
  "cvc_check": "pass",
  "dynamic_last4": null,
  "exp_month": 12,
  "exp_year": 2022,
  "fingerprint": "j4vVwU8z2TRy6rdF",
  "funding": "credit",
  "last4": "4242",
  "metadata": [],
  "name": null,
  "tokenization_method": null
}
